### ISSUE TITLE
Installing with Pip on Mac leads to ImportError

### ISSUE THREAD

**Issue by rsayn** [Quantco/tabmat#313]
Hello! I tried installing GLUM with Pip, but when I try to import it I get the following error:

```
>>> import glum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path-to-working-directory>.venv/lib/python3.8/site-packages/glum/__init__.py", line 3, in <module>
    from ._distribution import (
  File "<path-to-working-directory>.venv/lib/python3.8/site-packages/glum/_distribution.py", line 8, in <module>
    from tabmat import (
  File "<path-to-working-directory>.venv/lib/python3.8/site-packages/tabmat/__init__.py", line 1, in <module>
    from .categorical_matrix import CategoricalMatrix
  File "<path-to-working-directory>.venv/lib/python3.8/site-packages/tabmat/categorical_matrix.py", line 170, in <module>
    from .ext.categorical import (
ImportError: dlopen(<path-to-working-directory>.venv/lib/python3.8/site-packages/tabmat/ext/categorical.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_barrier'
```

My machine is a Mac M1 with MacOS Sonoma 14.0.

I'm assuming some compiler / linker flags are missing somewhere, however I couldn't find any install information in the docs.

Unfortunately installing with Conda is not an option, as I have to make this work with Poetry / PDM 😅

**Comment by MarcAntoineSchmidtQC** [comment]
I am able to replicate your issue. I still don't have a fix but I am working on it.

**Comment by rsayn** [comment]
Thanks! 

For the time being I managed to "hack" my PDM setup to reuse an existing Micromamba environment, and installed Glum and Tabmat with that.

It kinda works, but syncing the two is a pain so a fix would be super appreciated 👍

**Comment by jtilly** [comment]
Looks a lot like https://github.com/Quantco/tabmat/issues/220#issuecomment-1677012209, which was presumably fixed in https://github.com/Quantco/tabmat/pull/290. Maybe [this ](https://github.com/Quantco/tabmat/pull/290#discussion_r1295830006) wasn't as innocuous as it seemed?

**Comment by MarcAntoineSchmidtQC** [comment]
I think you are right @jtilly. Our previous releases on arm were broken because they were missing the `.dylibs` folder. I tested  a release on test.pypi and we now have it. I'll do a new release right now.

**Comment by MarcAntoineSchmidtQC** [comment]
The latest 3.1.11 release did fix the original issue, but didn't fix all the problems with the apple silicon wheel. #315 should fix the remaining issue. I'll do a release once it is merged.

**Comment by MarcAntoineSchmidtQC** [comment]
This issue was fixed with #317. I'm currently preparing the 3.1.12 release, which will contain the fix.

**Comment by rsayn** [comment]
Awesome! Thanks. I still cannot see the release on PyPI, I guess it will take a while longer 😄
